BILLING_WEBHOOK_PROCESS_JOB_TYPE = "billing.webhook.process"
BILLING_WEBHOOK_PROCESS_PAYLOAD_VERSION = 1

__all__ = [
    "BILLING_WEBHOOK_PROCESS_JOB_TYPE",
    "BILLING_WEBHOOK_PROCESS_PAYLOAD_VERSION",
]
